services:
  postgres2:
    image: postgres:16
    container_name: postgres2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:v11.2.0
    container_name: postgrest
    depends_on:
      - postgres2
    environment:
      PGRST_DB_URI: postgres://admin:admin@postgres:5432/mydb
      PGRST_DB_ANON_ROLE: anon
      PGRST_SERVER_PORT: 3000
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9100:9000" # S3 API
      - "9101:9001" # Web UI
    volumes:
      - minio_data:/data

  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: milvus-pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command:
      - etcd
      - --name=etcd
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd=http://0.0.0.0:2380
    volumes:
      - ./volumes/etcd:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"

  milvus:
    image: milvusdb/milvus:v2.6.0
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio

volumes:
  etcd_data:
  postgres_data:
  minio_data:
  milvus_data:
