apiVersion: v1
kind: Namespace
metadata:
  name: milvus
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: milvus
  labels:
    app: milvus
spec:
  type: NodePort
  selector:
    app: milvus
  ports:
    - name: milvus
      port: 19530
      targetPort: 19530
      nodePort: 30030
    - name: metrics
      port: 9091
      targetPort: 9091
      nodePort: 30091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: milvus
  labels:
    app: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:v2.2.13
          imagePullPolicy: IfNotPresent
          args: ["milvus", "run", "standalone"]
          ports:
            - containerPort: 19530
            - containerPort: 9091
          volumeMounts:
            - mountPath: /var/lib/milvus
              name: milvus-data
      volumes:
        - name: milvus-data
          emptyDir: {}
